name: Maven Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Import gpg key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg_key.asc
          gpg --batch --import gpg_key.asc
          del gpg_key.asc

      - name: Build with Maven
        run: mvn -B compile -P build-natives-win

      - name: Publish to Maven Central
        run: mvn -B deploy -s ${{ github.workspace }}/settings.xml "-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
