name: Maven Develop Build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${env.OSSRH_USERNAME}
          server-password: ${env.OSSRH_TOKEN}
          settings-path: ${{ github.workspace }}

      - name: Import gpg key
        run: |
          cat ${{ github.workspace }}/settings.xml
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg_key.asc
          gpg --batch --import gpg_key.asc
          del gpg_key.asc

      - name: Build natives
        run: mvn -B compile -P build-natives-win

      - name: Package jar
        run: mvn -B deploy -s ${{ github.workspace }}/settings.xml "-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: dev-artifact
          path: target/*.jar
