name: Maven Develop Build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -P build-natives-win

      - uses: actions/upload-artifact@v3
        with:
          name: dev-artifact
          path: target/*.jar
